
project_id = "svnockyhgohttzgbgydo"
# List of function entrypoints
entrypoints = [
  "generate-ads/index.ts",
  "generate-image/index.ts", 
  "optimize-ads/index.ts",
  "create-checkout-session/index.ts",
  "ad-account-auth/index.ts"
]
