
project_id = "svnockyhgohttzgbgydo"
# List of function entrypoints
entrypoints = [
  "generate-ads/index.ts",
  "generate-image/index.ts", 
  "optimize-ads/index.ts",
  "create-checkout-session/index.ts",
  "ad-account-auth/index.ts",
  "webhook-handler/index.ts",
  "generate-banner-image/index.ts",
  "create-oauth-states/index.ts",
  "analyze-website/index.ts",
  "get-analysis-cache-status/index.ts"
]
