
name = "cleanup-storage"
entrypoint = "index.ts"
envs = ["SUPABASE_URL", "SUPABASE_SERVICE_ROLE_KEY"]
# Run every 6 hours to aggressively clean up storage
schedule = { cron = "0 */6 * * *" }  # Runs every 6 hours
