// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncvffbkavcqkwbklicml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jdmZmYmthdmNxa3dia2xpY21sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNDMxNjksImV4cCI6MjA1NzcxOTE2OX0.Pya6pYmvMB1cwmbNueOl_v0MM-RS7gcSJSMQ4vsBL1c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);